services:
  postgres:
    container_name: ds_postgres
    image: postgres:17
    restart: on-failure
    environment:
      POSTGRES_DB: directory_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5436:5432
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
  seq:
    image: datalust/seq:latest
    container_name: ds_seq
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=password
    ports:
      - 5341:5341
      - 8081:80
volumes:
  postgres-data:   